### ISSUE TITLE
Error: unexpected keyword argument 'allow_unverified'

### ISSUE THREAD

**Issue by bayonne** [pypa/pep470#6]
pep470 package responds with:

```
Traceback (most recent call last):
  File "/usr/local/bin/pep470", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pep470/cli.py", line 39, in pep470
    session=session,
TypeError: __init__() got an unexpected keyword argument 'allow_unverified'
```

pep470 Version: 15.0
python 2.7.6

**Comment by bayonne** [comment]
I updated pip to 8.0.2 and pip.index.PackageFinder has changed.
